## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [120]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [121]:
print('Numpy version: '+str(np.version.version))
#pd.show_versions()

Numpy version: 1.16.5


2. Crear un arreglo 1D con enteros positivos aleatorios

In [11]:
np.random.randint(100, size=10)

array([81, 39, 68, 51, 93, 34, 60, 23, 82, 46])

3. Crear un arreglo booleano

In [18]:
tf = np.array([True, False])
tf

a = np.random.choice(tf, int(10)) 
a

array([ True, False])

4. Extraer los items que sean divisibles en 3.

In [3]:
matrix_int = np.random.randint(1000, size=10)

a5b=matrix_int % 3==0
print(a5b)
print(matrix_int)
#Arreglo de los valores dados por el filtro
a5=matrix_int[a5b]
print(a5)

[ True False  True False False False False False False False]
[681 164 555 781 725 238  38 364 169 244]
[681 555]


5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [30]:
random_array = np.random.choice(a=[False, True], size=6)
print(random_array)
print()
np.reshape(random_array, [3, 2])



[ True False False False  True  True]



array([[ True, False],
       [False, False],
       [ True,  True]])

6. Obtén los items comunes entre dos arreglos

In [4]:
a1 = [1,56,34,3,5,78,25]
a2 = [56,78,4,25,9,10,9]

np.intersect1d(a1, a2)

array([25, 56, 78])

7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [122]:
rando_ints=np.random.randint(10, size=10)
print(rando_ints)
media=rando_ints.mean()
print('media:'+str(media))
res=np.logical_and(rando_ints >= media-2, rando_ints <= media+2)

#print(res)
rf=rando_ints[res]
print(rf)


[6 9 1 9 7 9 8 1 6 2]
media:5.8
[6 7 6]


8. Muestra solo 3 decimales en un vector.

In [28]:
v = np.random.randn(10)
np.round(v, decimals=3)


array([-1.485,  0.346,  1.174, -0.212, -0.006,  1.05 ,  0.19 ,  1.206,
        0.543, -1.383])

9. Crea una atriz de 3x3 con los valores del 0 a 8

In [83]:
np.arange(9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [84]:
arreglo=np.array([1,2,0,0,4])
r=np.where(arreglo != 0)
r


(array([0, 1, 4], dtype=int64),)

11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [123]:
v30 = np.random.randint(100, size=30)
print(v30)
print(v30.mean())

[48 99 95 65 92 19 44 45 23 21 19 87  2 18 73 27 35 23 24  7 69 68 28 34
 29 46 90  8 52 25]
43.833333333333336


12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [74]:
farray = np.ones((5,5))
farray[1:-1,1:-1]=0
farray

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [124]:
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])
#3 * 0.1
0.3 == 3 * 0.1

#n=np.around(np.array([3*0.1]),1)

#0.3 == n

False


14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [30]:
ma=np.random.randint(0,19,(5,5))
ma

array([[ 1,  9,  4,  4, 14],
       [16,  7,  6, 14, 17],
       [16, 13,  7, 16,  8],
       [12,  4,  1, 14,  0],
       [15, 15, 18,  6, 12]])

In [102]:
#ma.diagonal(0)
diag=np.arange(4)
#diag
ma[diag,diag+1]=diag+1
ma

array([[ 1,  1,  4,  4, 14],
       [16,  7,  2, 14, 17],
       [16, 13,  7,  3,  8],
       [12,  4,  1, 14,  4],
       [15, 15, 18,  6, 12]])

15. Normaliza una matriz aleatoria de 5x5

In [118]:
ma = np.random.randint(0, 25, 25).reshape(5, 5)
print(ma)
print()
row_sums = ma.sum(axis=1)
print(row_sums)
print()
f = ma / row_sums[:, np.newaxis]
print(f)


[[ 6 12 18 15  4]
 [ 5  3 18 24 23]
 [22 12  5 17  6]
 [15 12  7 22  8]
 [ 8  5  8  0  1]]

[55 73 62 64 22]

[[0.10909091 0.21818182 0.32727273 0.27272727 0.07272727]
 [0.06849315 0.04109589 0.24657534 0.32876712 0.31506849]
 [0.35483871 0.19354839 0.08064516 0.27419355 0.09677419]
 [0.234375   0.1875     0.109375   0.34375    0.125     ]
 [0.36363636 0.22727273 0.36363636 0.         0.04545455]]


# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [40]:
import pandas as pd
print(pd.__version__)
#print(pd.show_versions())

0.25.1


Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [32]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [33]:
df=pd.DataFrame(data=data,index=labels)
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [35]:
#df.describe()
df.describe(include='all')

animal       age     visits priority
count      10  8.000000  10.000000       10
unique      3       NaN        NaN        2
top       dog       NaN        NaN       no
freq        4       NaN        NaN        6
mean      NaN  3.437500   1.900000      NaN
std       NaN  2.007797   0.875595      NaN
min       NaN  0.500000   1.000000      NaN
25%       NaN  2.375000   1.000000      NaN
50%       NaN  3.000000   2.000000      NaN
75%       NaN  4.625000   2.750000      NaN
max       NaN  7.000000   3.000000      NaN

4. Regresa las primeras 3 filas del DataFrame

In [42]:
df.iloc[0:3,:]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [44]:
col_name = {'animal':'Animal','age':'Edad','visits':'Visitas','priority':'Prioridad'}
df.columns = df.columns.map(col_name)
df

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no

6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [46]:
df[['Animal','Edad']]

Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0

7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [119]:
df[df['Visitas'] > 3]

Empty DataFrame
Columns: [Animal, Edad, Visitas, Prioridad, COUNTER]
Index: []

8. ¿Cuáles son las filas donde la edad es NaN?

In [56]:
res=df['Edad'].isnull()
print(df[res])

  Animal  Edad  Visitas Prioridad
d    dog   NaN        3       yes
h    cat   NaN        1       yes


9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [55]:
cond=(df['Edad'] >=2) & (df['Edad'] <= 4)
print(df[cond])

  Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no


10. ¿Cuál es el total de todas las visitas?

In [60]:
suma=df['Visitas'].sum()
print(suma)

19


12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [66]:
df['COUNTER'] =1       #initially, set that counter to 1.
group_data = df.groupby(['Animal'])['COUNTER'].sum() #sum function
print(group_data)

Animal
cat      4
dog      4
snake    2
Name: COUNTER, dtype: int64


13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [70]:
#df["column1"].replace({"a": "x", "b": "y"}, inplace=True)
#print(df)

df['Prioridad'].replace({"yes":True,"no":False}, inplace=True)
print(df)

  Animal  Edad  Visitas Prioridad  COUNTER
a    cat   2.5        1      True        1
b    cat   3.0        3      True        1
c  snake   0.5        2     False        1
d    dog   NaN        3      True        1
e    dog   5.0        2     False        1
f    cat   2.0        3     False        1
g  snake   4.5        1     False        1
h    cat   NaN        1      True        1
i    dog   7.0        2     False        1
j    dog   3.0        1     False        1


14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [71]:
df = df.sort_values(["Edad", "Visitas"], ascending = (False, True))
print(df)

  Animal  Edad  Visitas Prioridad  COUNTER
i    dog   7.0        2     False        1
e    dog   5.0        2     False        1
g  snake   4.5        1     False        1
j    dog   3.0        1     False        1
b    cat   3.0        3      True        1
a    cat   2.5        1      True        1
f    cat   2.0        3     False        1
c  snake   0.5        2     False        1
h    cat   NaN        1      True        1
d    dog   NaN        3      True        1


15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [77]:

proms = df.groupby(['Animal'])['Edad','Visitas'].mean() 
print(proms)

        Edad  Visitas
Animal               
cat      2.5      2.0
dog      5.0      2.0
snake    2.5      1.5


# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto